### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by darxriggs**
I suggest to review this pull request commit by commit as each one covers a different aspect.

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @ohadmuch, as some time already passed since this pull-request was created, I just wanted to check if it can be merged?

**Comment by darxriggs** [comment]
Hi @ohadmuch, I rebased on master, resolved the merge conflicts and additionally also fixed the FindBugs Maven plugin problem.

**Comment by darxriggs** [comment]
I am not planning to add more commits.
The pull request is ready to be merged.

**Comment by ohadmuch** [comment]
@darxriggs hey,  sorry for the delay.
Part of the things you wrote were fixed in the last versions , the other things are related to our coding conventions, so i'm closing this PR.
thanks

**Comment by darxriggs** [comment]
Let me try one more time - I cannot see for example cad2352 to be fixed on master.

**Pull request closed without merging**
